services:
  panda-bot:
    volumes:
      - ./backups:${BACKUP_DIR}
    container_name: panda_bot
    working_dir: /panda_bot
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "python bot.py"
    depends_on:
      - redis
      - db
    environment:
      - TZ=Europe/Moscow
  redis:
    image: redis:7
    restart: always
    ports:
      - 6000:6379
    volumes:
      - redis_data:/data
    environment:
      - TZ=Europe/Moscow

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 6543:${PG_PORT}
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_HOST}
      - TZ=Europe/Moscow

  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    env_file: ".env"
    environment:
      - TZ=Europe/Moscow

volumes:
  postgres_data:
  redis_data:
  mongo_data:
